### ISSUE TITLE
Missing environment variables: CHAINPOINT_NODE_API_BASE_URI

### ISSUE THREAD

**Issue by trakout** [chainpoint/chainpoint-cli#1]
This happens even when --server is specified.
README needs an update for the stuff `envalid` is doing.

Edit: Everything works fine on OSX. This error is happening on Ubuntu 16.04.

**Comment by grempe** [comment]
Thanks. We'll look into it.

**Comment by grempe** [comment]
This issue has been resolved in an earlier release. If you can still reproduce please feel free to ask that this issue be re-opened.
