### ISSUE TITLE
Any command I run I get the same error

### ISSUE THREAD

**Issue by cleanunicorn** [chainpoint/chainpoint-cli#2]
This is the error I get

```
Unable to discover a random Node instance
```

I've installed it throug `npm`

Even `version` outputs the error
```
> chp version
Unable to discover a random Node instance
```

Or even if I specify one of my nodes with `-s http://123.123.123.123` (adding real ip) I get the same error

**Comment by grempe** [comment]
Sorry for the delay in responding to this issue. I believe whatever issue was present at the time with that earlier version of our CLI is no longer an issue. If you can still reproduce please feel free to ask that this issue be re-opened.

Cheers.
